twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
      social_facebook: '%social_facebook%'
      social_twitter: '%social_twitter%'
      social_youtube: '%social_youtube%'
      donation_link: '%donation_link%'
      GA_TRACKING_ID: '%env(GA_TRACKING_ID)%'
      recaptcha_id: '%env(RECAPTCHA_ID)%'

